# Pre-commit hooks configuration for SmartFlowAI
repos:
  # Black - formatowanie kodu Python
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # isort - sortowanie importów
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # flake8 - linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203, W503]

  # mypy - type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports]

  # Bandit - security linting
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, ., -f, txt]
        exclude: ^tests/

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Sprawdzanie składni YAML
      - id: check-yaml
      # Sprawdzanie składni JSON
      - id: check-json
      # Sprawdzanie składni TOML
      - id: check-toml
      # Usuwanie białych znaków na końcu linii
      - id: trailing-whitespace
      # Dodawanie nowej linii na końcu pliku
      - id: end-of-file-fixer
      # Sprawdzanie dużych plików
      - id: check-added-large-files
        args: [--maxkb=1000]
      # Sprawdzanie merge conflicts
      - id: check-merge-conflict
      # Sprawdzanie case conflicts
      - id: check-case-conflict
      # Sprawdzanie wykonalnych plików tekstowych
      - id: check-executables-have-shebangs

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]

  # Sprawdzanie requirements.txt
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check

  # Sprawdzanie commitów
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.6.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

# Konfiguracja globalna
default_language_version:
  python: python3.11

# Pliki do wykluczenia
exclude: |
  (?x)^(
    \.git/|
    \.pytest_cache/|
    __pycache__/|
    \.venv/|
    venv/|
    build/|
    dist/|
    \.eggs/|
    .*\.egg-info/
  )$

# Fail fast - zatrzymaj na pierwszym błędzie
fail_fast: false

# Minimum version
minimum_pre_commit_version: 3.3.0
