version: '3.8'

services:
  # Aplikacja SmartFlowAI
  smartflowai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartflowai-app
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=development
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - smartflow-network

  # Redis dla cache (opcjonalnie)
  redis:
    image: redis:7-alpine
    container_name: smartflowai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - smartflow-network

  # Nginx jako reverse proxy (opcjonalnie)
  nginx:
    image: nginx:alpine
    container_name: smartflowai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - smartflowai
    restart: unless-stopped
    networks:
      - smartflow-network

volumes:
  redis_data:

networks:
  smartflow-network:
    driver: bridge 