# Plik: .streamlit/config.toml
# .streamlit/config.toml - Konfiguracja Streamlit dla SmartFlowAI

[global]
# Ustawienia globalne
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Ustawienia serwera
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
# Ustawienia przeglądarki
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Dark Mode dla SmartFlowAI 🌙
base = "dark"
primaryColor = "#00D4AA"          # Mint green - akcenty i przyciski
backgroundColor = "#0E1117"       # Główne tło - ciemne
secondaryBackgroundColor = "#262730"  # Panele boczne - szare
textColor = "#FAFAFA"            # Tekst - biały
font = "sans serif"

# Alternatywa Light Mode (zakomentowane):
# base = "light"
# primaryColor = "#FF6B6B"          # Coral - akcenty
# backgroundColor = "#FFFFFF"       # Białe tło
# secondaryBackgroundColor = "#F0F2F6"  # Jasno szare panele
# textColor = "#262730"             # Ciemny tekst

[logger]
# Ustawienia logowania
level = "info"
messageFormat = "%(asctime)s %(message)s"